// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace FormCenso.DataAccess.Entities
{
    public partial class FormcensoContext : DbContext
    {
        public FormcensoContext()
        {
        }

        public FormcensoContext(DbContextOptions<FormcensoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<tbCenso> tbCenso { get; set; }
        public virtual DbSet<tbCentrosVotacion> tbCentrosVotacion { get; set; }
        public virtual DbSet<tbColonias> tbColonias { get; set; }
        public virtual DbSet<tbDepartamentos> tbDepartamentos { get; set; }
        public virtual DbSet<tbMunicipios> tbMunicipios { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "Modern_Spanish_CI_AS");

            modelBuilder.Entity<tbCenso>(entity =>
            {
                entity.HasKey(e => e.censo_Id)
                    .HasName("PK__tbCenso__2081BB9E80EECA32");

                entity.HasIndex(e => e.censo_Identidad, "UQ__tbCenso__91767702600828AD")
                    .IsUnique();

                entity.Property(e => e.censo_Apellidos)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.censo_FechaNac).HasColumnType("date");

                entity.Property(e => e.censo_Identidad)
                    .IsRequired()
                    .HasMaxLength(13)
                    .IsUnicode(false);

                entity.Property(e => e.censo_Nombres)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.censo_Sexo)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false)
                    .IsFixedLength(true);

                entity.Property(e => e.censo_Telefono)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.HasOne(d => d.cenvot)
                    .WithMany(p => p.tbCenso)
                    .HasForeignKey(d => d.cenvot_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbCentrosVotacion>(entity =>
            {
                entity.HasKey(e => e.cenvot_Id)
                    .HasName("PK__tbCentro__178557BF03BF2E58");

                entity.Property(e => e.cenvot_Nombre)
                    .IsRequired()
                    .HasMaxLength(250);

                entity.HasOne(d => d.col)
                    .WithMany(p => p.tbCentrosVotacion)
                    .HasForeignKey(d => d.col_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbColonias>(entity =>
            {
                entity.HasKey(e => e.col_Id)
                    .HasName("PK__tbColoni__57826CAFCD14393E");

                entity.Property(e => e.col_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.Property(e => e.muni_Id)
                    .IsRequired()
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.HasOne(d => d.muni)
                    .WithMany(p => p.tbColonias)
                    .HasForeignKey(d => d.muni_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<tbDepartamentos>(entity =>
            {
                entity.HasKey(e => e.depto_Id)
                    .HasName("PK__tbDepart__7A296A2A925DB1F1");

                entity.Property(e => e.depto_Id)
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.depto_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100);
            });

            modelBuilder.Entity<tbMunicipios>(entity =>
            {
                entity.HasKey(e => e.muni_Id)
                    .HasName("PK__tbMunici__CF2E0951F7B9E6C0");

                entity.Property(e => e.muni_Id)
                    .HasMaxLength(4)
                    .IsUnicode(false);

                entity.Property(e => e.depto_Id)
                    .IsRequired()
                    .HasMaxLength(2)
                    .IsUnicode(false);

                entity.Property(e => e.muni_Descripcion)
                    .IsRequired()
                    .HasMaxLength(100);

                entity.HasOne(d => d.depto)
                    .WithMany(p => p.tbMunicipios)
                    .HasForeignKey(d => d.depto_Id)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}