// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using FormCenso.DataAccess.Entities;

namespace FormCenso.DataAccess.Entities
{
    public static class FormcensoContextProceduresExtensions
    {
        public static FormcensoContextProcedures GetProcedures(this FormcensoContext context)
        {
            return new FormcensoContextProcedures(context);
        }
    }

    public partial class FormcensoContextProcedures
    {
        private readonly FormcensoContext _context;

        public FormcensoContextProcedures(FormcensoContext context)
        {
            _context = context;
        }

        public async Task<UDP_tbCenso_VotoResult[]> UDP_tbCenso_VotoAsync(int? Id, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Id",
                    Value = Id ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UDP_tbCenso_VotoResult>("EXEC @returnValue = [dbo].[UDP_tbCenso_Voto] @Id", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public async Task<UDP_tbCensoList_BuscarResult[]> UDP_tbCensoList_BuscarAsync(string identidad, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "identidad",
                    Size = 13,
                    Value = identidad ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<UDP_tbCensoList_BuscarResult>("EXEC @returnValue = [dbo].[UDP_tbCensoList_Buscar] @identidad", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
