// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FormCenso.DataAccess.Entities
{
    public partial class tbCenso
    {
        public int censo_Id { get; set; }
        public string censo_Identidad { get; set; }
        public string censo_Nombres { get; set; }
        public string censo_Apellidos { get; set; }
        public DateTime censo_FechaNac { get; set; }
        public string censo_Telefono { get; set; }
        public string censo_Sexo { get; set; }
        public int cenvot_Id { get; set; }
        public int censo_NumMesa { get; set; }
        public int censo_NumLinea { get; set; }
        public bool? censo_Voto { get; set; }

        public virtual tbCentrosVotacion cenvot { get; set; }
    }
}