// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FormCenso.DataAccess.Entities
{
    public partial class tbCentrosVotacion
    {
        public tbCentrosVotacion()
        {
            tbCenso = new HashSet<tbCenso>();
        }

        public int cenvot_Id { get; set; }
        public int col_Id { get; set; }
        public string cenvot_Nombre { get; set; }

        public virtual tbColonias col { get; set; }
        public virtual ICollection<tbCenso> tbCenso { get; set; }
    }
}