// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FormCenso.DataAccess.Entities
{
    public partial class tbColonias
    {
        public tbColonias()
        {
            tbCentrosVotacion = new HashSet<tbCentrosVotacion>();
        }

        public int col_Id { get; set; }
        public string muni_Id { get; set; }
        public string col_Descripcion { get; set; }

        public virtual tbMunicipios muni { get; set; }
        public virtual ICollection<tbCentrosVotacion> tbCentrosVotacion { get; set; }
    }
}