// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FormCenso.DataAccess.Entities
{
    public partial class tbDepartamentos
    {
        public tbDepartamentos()
        {
            tbMunicipios = new HashSet<tbMunicipios>();
        }

        public string depto_Id { get; set; }
        public string depto_Descripcion { get; set; }

        public virtual ICollection<tbMunicipios> tbMunicipios { get; set; }
    }
}