// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace FormCenso.DataAccess.Entities
{
    public partial class tbMunicipios
    {
        public tbMunicipios()
        {
            tbColonias = new HashSet<tbColonias>();
        }

        public string muni_Id { get; set; }
        public string depto_Id { get; set; }
        public string muni_Descripcion { get; set; }

        public virtual tbDepartamentos depto { get; set; }
        public virtual ICollection<tbColonias> tbColonias { get; set; }
    }
}