// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace FormCenso.DataAccess.Entities
{
    public partial class UDP_tbCensoList_BuscarResult
    {
        public int censo_Id { get; set; }
        public string censo_Identidad { get; set; }
        public string NombreCompleto { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        public string Colonia { get; set; }
        public string CentroVotacion { get; set; }
        public int NumeroLinea { get; set; }
        public int NumeroMesa { get; set; }
        public bool? Voto { get; set; }
    }
}
